apiVersion: v1
kind: Service
metadata:
  name: epoch5-stable
  labels:
    app: epoch5
    version: stable
spec:
  selector:
    app: epoch5
    version: stable
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: epoch5-canary
  labels:
    app: epoch5
    version: canary
spec:
  selector:
    app: epoch5
    version: canary
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epoch5-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - epoch5.yourdomain.com
    secretName: epoch5-tls
  rules:
  - host: epoch5.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: epoch5-stable
            port:
              number: 80