name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Make scripts executable
        run: chmod +x epoch5.sh test_epoch5.py
      
      - name: Run Python compilation tests
        run: npm run test:python
        
      - name: Run shell script syntax tests  
        run: npm run test:shell
        
      - name: Run integration tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy
        run: echo "Deployment would happen here for main branch" # Replace with actual deployment commands
