name: Update Coverage Badge

on:
  push:
    branches: [main]
    paths:
      - 'coverage.xml'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage-badge
      
      - name: Extract coverage percentage
        run: |
          echo "COVERAGE_PCT=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(float(root.attrib['line-rate']) * 100)")" >> $GITHUB_ENV
          echo "Coverage: ${{ env.COVERAGE_PCT }}%"
      
      - name: Generate coverage badge
        run: |
          mkdir -p docs/badges
          coverage-badge -o docs/badges/coverage-badge.svg -f -p ${{ env.COVERAGE_PCT }}
      
      - name: Commit updated badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/badges/coverage-badge.svg
          git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
          git push
